### ISSUE TITLE
Create mockups of dynamic data visualizations in data paper layout

### ISSUE THREAD

**Issue by laurenwalker** [DataONEorg/collections-portals-schemas#14]
We created the data paper wireframes already. We want to expand on that wireframe and create a hifi mockup that represents what the data paper will actually look like in the UI, focusing on fonts, colors, alignment, and other "pixel perfect" design.

This mockup can be shown the SASAP working groups for feedback since it will look more like a user interface.

**Comment by robyngit** [comment]
See this issue for implementing data visualizations in portals: https://github.com/NCEAS/metacatui/issues/1383
