### ISSUE TITLE
create DBO Arctic project document

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/collections-portals-schemas#42]
Create a project document showing the DBO Arctic project info serialized into the emerging project description format.

**Comment by robyngit** [comment]
**Additional details:**
- We need to support things like vessel searching, and adding international flags to the logos section.
- For the filters, we would like to emulate the functionality found [here](http://dbo.eol.ucar.edu/). Their [cruise data page](https://www.pmel.noaa.gov/dbo/2016-cruise-data) might also provide details.

**Comment by csjx** [comment]
Hi @robyngit - When you create a DBO project definition document, please upload it to both https://dev.nceas.ucsb.edu and https://test.arcticdata.io. 
Please include an `AccessPolicy` that has `read/write/changePermission` permissions for the `CN=knb-data-admins,DC=dataone,DC=org` and the `CN=arctic-data-admins,DC=dataone,DC=org` groups respectively.  Also, assign the `seriesId` in the system metadata which is found here:

https://github.com/NCEAS/metacatui/blob/b713766a028a8b6d6c1d77b96acc17a58127577f/src/js/themes/arctic/models/AppModel.js#L129

That's the `seriesId` that allows us to navigate to `/projects/DBO`.

**Comment by robyngit** [comment]
Initial DBO project xml is now available on `dev.nceas` with pid `urn:uuid:d4f20af6-0134-4bfa-8204-eb3ee5152ad7` and `tests.arcticdata` with pid `urn:uuid:62d1add2-d3dd-470e-b31e-0e82ccb23c72`. The seriesID (sid) for both is `urn:node:93834148-30ce-420d-8d6d-b6690d93b9bc`
