### ISSUE TITLE
Decide how to semantically link project personnel to users

### ISSUE THREAD

**Issue by laurenwalker** [DataONEorg/collections-portals-schemas#6]
Will personnel in the schema each need an ORCID, or is a first and last name the only requirement?

How can we semantically link a person listed in the project personnel with a user in our system to definitely link to a user profile in the UI?

**Comment by robyngit** [comment]
Personnel are linked to portals using the `associatedParty` element, which is an extension of [EML's `ResponsibleParty`](https://eml.ecoinformatics.org/schema/eml-party_xsd.html#ResponsibleParty) element - it requires at least an `individualName`, `organizationName`, or `positionName`. It can include an ORCID as a `userId`.
