### ISSUE TITLE
create Permafrost WG project document

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/collections-portals-schemas#67]
The Arctic WG created a web page (https://arcticdata.io/reconciling-historical-and-contemporary-trends-in-terrestrial-carbon-exchange-of-the-northern-permafrost-zone/) and would be a good example of the type of project page we want to enable at the ADC.  It would make another good example of one that would be useful for Arctic.

@laurenwalker, @csjx, and @robyngit could review this page for features for the system.

@mpsaloha could provide guidance on what is useful and was involved in the design and data collation.

**Comment by jeanetteclark** [comment]
Great idea - this should be easy to put together. 

@mpsaloha do you have a list of the datasets that the group would want to show in the "Data" tab of their project page? This would include any of their source datasets from the ADC that they are using in synthesis, and any derived datasets they published.

**Comment by jeanetteclark** [comment]
need to talk to Steven about this and just get a list of the carbon datasets

**Comment by stevenchong** [comment]
@jeanetteclark Here's a list of DOIs from Ted Schuur's Arctic Permafrost WG: https://docs.google.com/spreadsheets/d/1CN-LD1Wtny0FuhL4qBn8U7Pa8kODrBTjMHw4yOAfjk0/edit#gid=1436397416 . The list was made in March 2018, so you'll probably want to check for updates.
