### ISSUE TITLE
Update existing portal documents to new  schema

### ISSUE THREAD

**Issue by laurenwalker** [DataONEorg/collections-portals-schemas#74]
The SASAP, DBO, and CALM portals need to be updated to the new portals XML schema by the time the portals editor is deployed to production. These documents could be created in the new editor once it's nearly complete, but some manual editing will need to be done anyway since the MVP editor won't support all the features.

The latest collections schema is here: https://github.com/NCEAS/project-papers/blob/master/schemas/collections.xsd
The latest portal schema is here: https://github.com/NCEAS/project-papers/blob/master/schemas/portals.xsd

The primary changes are:
- collection definitions can now support date, boolean, and numeric filters in addition to regular text `<filter>`s
- collection definition filters can also support optional labels, which will display in the editor as human-readable labels for complex filters
- All images are of type ImageType
- `<textFilter>` nodes have been renamed to simply `<filter>`
- some element ordering has changed

The portal documents will now be validated against the schema when they are inserted, so things like elements out of order, empty elements, non-supported elements, wrong value types, etc. will cause the inserts to fail.

dev.nceas is the only MN right now that has these latest changes, so portal document uploads can be tested there.

**Comment by laurenwalker** [comment]
We're likely only about 1-2 weeks away from updating the KNB and Arctic Data Center with the new portal features, which means the existing portal docs need to be ready to be replaced/updated at that time.

**Comment by jeanetteclark** [comment]
The following portal docs have been updated and are up on dev.nceas. Many of the image identifiers don't exist on `dev` but are on `prod`, so that will resolve itself once we move these updated copies to the production nodes

- [x] Permafrost
- [x] Calm
- [ ] DBO
- [x] SASAP

**Comment by laurenwalker** [comment]
Great, thanks Jeanette!

**Comment by laurenwalker** [comment]
I believe this is all completed - can you confirm @jeanetteclark ?

**Comment by jeanetteclark** [comment]
yup!
