### ISSUE TITLE
Tag 1.1.0 release

### ISSUE THREAD

**Issue by gothub** [DataONEorg/collections-portals-schemas#92]
Tag the 1.1.0 release so that these links are available:
- https://raw.githubusercontent.com/DataONEorg/collections-portals-schemas/1.1.0/schemas/portals.xsd
- https://raw.githubusercontent.com/DataONEorg/collections-portals-schemas/1.1.0/schemas/collections.xsd

Do links need to be made on https://purl.dataone.org?

Also, do the namespaces in portals.xsd and collections.xsd need to be updated as well?

**Comment by robyngit** [comment]
The 1.1.0 release is now tagged: https://github.com/DataONEorg/collections-portals-schemas/releases/tag/1.1.0
